Resources:
  SimpleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Tableindrift
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
